# Generated by Django 2.0.5 on 2020-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='', max_length=512, verbose_name='用处')),
                ('hostname', models.CharField(default='', max_length=32, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(db_index=True, default='0.0.0.0', unique=True, verbose_name='IP地址')),
                ('mac', models.CharField(default='00:00:00:00:00:00', max_length=32, verbose_name='MAC地址')),
                ('os', models.CharField(default='', max_length=32, verbose_name='操作系统')),
                ('mem', models.BigIntegerField(default=0, verbose_name='内存')),
                ('cpu', models.IntegerField(default=0, verbose_name='CPU')),
                ('disk', models.CharField(default='{}', max_length=512, verbose_name='硬盘')),
                ('sn', models.CharField(default='', max_length=128, verbose_name='服务器型号')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(verbose_name='最后一次检查时间')),
            ],
            options={
                'db_table': 'Host_server',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Host_server_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, default='0.0.0.0', unique=True, verbose_name='IP地址')),
                ('status', models.CharField(default='0', max_length=32, verbose_name='服务器状态')),
                ('Damage_times', models.IntegerField(default=0, verbose_name='故障次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(verbose_name='最后一次检查时间')),
            ],
            options={
                'db_table': 'Host_server_status',
                'ordering': ['id'],
            },
        ),
    ]
