# Generated by Django 2.0.5 on 2020-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_server_cpu_mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, default='0.0.0.0', unique=True, verbose_name='IP地址')),
                ('cpu_utilize', models.IntegerField(db_index=True, default=0, verbose_name='CPU')),
                ('mem_utilize', models.BigIntegerField(db_index=True, default=0, verbose_name='内存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(db_index=True, verbose_name='最后一次检查时间')),
                ('disk_utilize', models.CharField(default='{}', max_length=512, verbose_name='硬盘')),
            ],
            options={
                'db_table': 'Host_server_cpu_mem',
                'ordering': ['id'],
            },
        ),
    ]
