# Generated by Django 2.0.5 on 2020-01-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_server', '0002_host_server_cpu_mem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_server_cpu_mem',
            name='cpu_utilize',
            field=models.FloatField(db_index=True, default=0, verbose_name='CPU'),
        ),
    ]
