# Generated by Django 2.0.5 on 2020-01-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_server', '0003_auto_20200107_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_server_cpu_mem',
            name='mem_utilize',
            field=models.FloatField(db_index=True, default=0, verbose_name='内存'),
        ),
    ]
