# Generated by Django 2.0.5 on 2020-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_server', '0004_auto_20200107_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_server_cpu_mem',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, default='0.0.0.0', verbose_name='IP地址'),
        ),
    ]
