# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20180701_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': (('view_server', 'can view server'),)},
        ),
    ]
