# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-23 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconf',
            name='sql_content',
            field=models.TextField(default=None),
        ),
    ]
