# Generated by Django 2.0.5 on 2019-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlweb', '0002_dbconf_sql_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('db_user', models.CharField(max_length=128, verbose_name='用户')),
                ('db_password', models.CharField(max_length=128, verbose_name='密码')),
                ('host', models.CharField(max_length=16, verbose_name='数据库地址')),
                ('port', models.CharField(max_length=5, verbose_name='端口号')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'db_change',
                'ordering': ['id'],
            },
        ),
    ]
